name: Auto Deploy Frontend

on:
  push:
    branches: ["main"]

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup Node
        uses: actions/setup-node@v4
        with:
          node-version: 22

      - name: Install deps (only if needed)
        run: |
          if [ ! -d "node_modules" ]; then
            npm install
          fi

      - name: Build
        env:
          NODE_OPTIONS: "--max-old-space-size=4096"
        run: npm run build

      - name: Setup SSH
        uses: webfactory/ssh-agent@v0.9.0
        with:
          ssh-private-key: ${{ secrets.SSH_PRIVATE_KEY }}

      - name: Deploy dist to Server
        run: |
          rsync -avz --delete \
          -e "ssh -o StrictHostKeyChecking=no -o UserKnownHostsFile=/dev/null" \
          dist/ \
          ${{ secrets.SERVER_USER }}@${{ secrets.SERVER_IP }}:/www/wwwroot/Internal-Project /
