name: Auto Deploy to Server

on:
  push:
    branches: ["main"]

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Code
        uses: actions/checkout@v3

      - name: Setup SSH Agent
        uses: webfactory/ssh-agent@v0.5.4
        with:
          ssh-private-key:-----BEGIN OPENSSH PRIVATE KEY-----
b3BlbnNzaC1rZXktdjEAAAAABG5vbmUAAAAEbm9uZQAAAAAAAAABAAACFwAAAAdzc2gtcn
NhAAAAAwEAAQAAAgEAopd5eEq3XpEcB32sb+3/PFB9fgfN8YwZ9FvlqWcCcGSZLsGuEJJb
D3P6p2kSS6Gw68TuFBX8ZHdN0MVlRMxq6LmGdB0Mv7jcORwy/Kg8pxaSJ1pyAkrk+XEL3Q
egAAO+9sQyvJT30+FZ88kblToZ57te2bKKrKHPvA27Br8gEJnSjaqeB4XRiCUtqiKEtvFm
iuiJneikO824AlezH2+rkMz2NMkazef7JTIQFpJs9Rym37+Nd6eo9eU/9kZJtQ7vxA6h74
BXW6sjAuhgKTXsJyD5+/3WHaoAShnIbu4WS6yNBpimzKXyglCjthWbF4quFB94PEVUap/S
5N95visEyXHZpDQLwmhoF/yvODx1Gvon4BTTAfhAE+cPulhjpdV83Ns2tEU7wLKd4uKxq3
SdhXRXd2sn4pmaujzulrNo70oikW9zKd3duMhdxT+qlDw0OgvceZqnsbnJ0fiL6qWnej5Y
f8mZpMEX/my8qVR9Ije04NbhDkgvBXkx+TI+Q7KREQf6hLwetONoiHTyGWHKT1aFlcAmaw
F91oJgjBqjWma5Z+a6NNU8YtL79BfG50n77xKePZdSXmcJfyn3zwupYTQzRuFrwrDoh9gO
SxfjcVY/uXsZ2LAL3Vzly2tE+y0Q1Xy9ZzxuyNYUKG2GloUF6UCdOOLEXDTUgEzR6+Vgmf
MAAAdIqA9ndqgPZ3YAAAAHc3NoLXJzYQAAAgEAopd5eEq3XpEcB32sb+3/PFB9fgfN8YwZ
9FvlqWcCcGSZLsGuEJJbD3P6p2kSS6Gw68TuFBX8ZHdN0MVlRMxq6LmGdB0Mv7jcORwy/K
g8pxaSJ1pyAkrk+XEL3QegAAO+9sQyvJT30+FZ88kblToZ57te2bKKrKHPvA27Br8gEJnS
jaqeB4XRiCUtqiKEtvFmiuiJneikO824AlezH2+rkMz2NMkazef7JTIQFpJs9Rym37+Nd6
eo9eU/9kZJtQ7vxA6h74BXW6sjAuhgKTXsJyD5+/3WHaoAShnIbu4WS6yNBpimzKXyglCj
thWbF4quFB94PEVUap/S5N95visEyXHZpDQLwmhoF/yvODx1Gvon4BTTAfhAE+cPulhjpd
V83Ns2tEU7wLKd4uKxq3SdhXRXd2sn4pmaujzulrNo70oikW9zKd3duMhdxT+qlDw0Ogvc
eZqnsbnJ0fiL6qWnej5Yf8mZpMEX/my8qVR9Ije04NbhDkgvBXkx+TI+Q7KREQf6hLwetO
NoiHTyGWHKT1aFlcAmawF91oJgjBqjWma5Z+a6NNU8YtL79BfG50n77xKePZdSXmcJfyn3
zwupYTQzRuFrwrDoh9gOSxfjcVY/uXsZ2LAL3Vzly2tE+y0Q1Xy9ZzxuyNYUKG2GloUF6U
CdOOLEXDTUgEzR6+VgmfMAAAADAQABAAACAAtiqm54ybv+uVG+kSajw227zS3YHUNYcv2g
U1+FB3yxu30bGIJ8kF48QHi2ONvAjmnUHnMCa+wbfQCtJSXa+Qy9TePJOcbrJDCzmTZsD+
M7bclnrsTn7bGYViMiKsGvGxFrziNUFltpIMPOrCnLXPXT/xS+r354AXRcgC49KZRzN3VI
In/9KB3UGXO1rklvptiVtAOxi/gygNVZKTSx7/elAp1rphh15PZHBsb6qSD44qgxLhZxtr
kq8BgUwyPBagGQOYxSr/6K6Ca5+V6pZS7QQyRMM1D2DvmHy9577MyO+eK7Kclgc+NNAxaR
dYzOeNlb4si43VJu4qiFDAdiOv5FNtuQaUqtPQcSp88qDxp6hSiNyjT7uTa+BHrbP9LfDv
tqiWIsc45rTTG8E/3vUpVdRlq7rG30mA4xHZGEoy04VoTlEYhH2nM+hHOca3XTAPeWgqwO
AtYsEXz0I6kO+AXaeL9vtUhAVLx62tQSaKV8nf5cwHyx6+MGIE45+wEgmfQnyFlEnu0VpT
yeL1DdJYCpzEnCRX/mZIZ7rarDam+B6qq/1H6YNi0uUM/hdnaz2mm2ydAt/t2DRi+y+Q2S
hLqENMHGU/9qtGfQWOxG/b2D+DIMcZcndNujx/MMnhKI2lPPf00ew277zEvGoGHvHHj6Kf
lt9YBWFlly361bMwJhAAABAEMu/TKBr1Ag2ipnAUeO7fTS5xnPqhOT3WxxXOFAHoEW1AVa
KlEQATjKteHhZtsRKVsM9ATjMjmqDYVVP0HErEXGxx9rCoHuOWJ/1P0hswYrZniMmijL1y
s0S2JLt8X3JjAIgjahgUDzpF4AHi+3a4E48rf1EyeazYofC5r8HLd8wzQ5os/NQIkiTNjD
KAkxH14QQRIcU9mQ8+f6E1LujDWcQdrdhsZ6wjfqNuesahR/nHgmpwHVfRI6rLJU57/ucJ
4kTacSV+5GoYkBzTYBSizEhxlB8gRtEx2bykc/Zjapyr7gkXpUHMIq/w/4AP448a2NTcyS
ESQ4g2Zc2dwduJoAAAEBANW8T9hyoZ3nHkfqH1ibwYf4wcxYqEZExUgBIZLD/2CPfRQEZl
fN+H39qkmshZZHJbQ1N0NdYBXLlkSKF2NdVh7A9pJor5Q9s2H1BYSKuXNaLtPQQIww8q/D
rOcqi7Iz5JHcWqmHrK3cSxuoN4w9uYxVwnulLLCcriDCelkYjRcQu8c+oA6i9BARtQQpuQ
u7dkdY5owHr63e1fpAhsa+0xp8IHxnLpIVfe6QVoR0ziSU+LDS8KWnc3FdhyugvVmDKlzF
1hA5upI3LJzWDGp8N8B4XfbfnAHvNtQ3US2/dPhXbMoNiEGKf9efaKV9iy3VzePFsus8M3
h7Hekk108nepkAAAEBAMK+KijazWB3I+VXXuTh/8/28McydWPOrUtysJ4dEPnEKEohdoCO
IeEbSa+G8YPlKbGDEUBcK01dO2xSxH6ecycFvUsiDfJFxQoMnD+3jIGPtSndRD3w/YhhcD
HyHfv7VlftxO4A9/Z7t3H2q+f7UIuU81EwsEHKElRvKddQ3051020+O7wLCwelVOPEQb2/
5FJlXMq1fiwJNX321AWeKv2TTdYM3sXow2UZ8CQ54Q4iWdq8bjlHj96BS83sSsZZKiNEI9
IOWECTAPRbODBhjSoWuYf/CkK9Zqj4LS7u3ihnZJ/cCgTKTeawIE08lDdNSaZEMHGlIKiy
kvEUT5+YvGsAAAAQSW50ZXJuYWwtcHJvamVjdAECAw==
-----END OPENSSH PRIVATE KEY-----

      - name: Deploy to Server
        run: |
          ssh -o StrictHostKeyChecking=no \
          ${{ secrets.SERVER_USER }}@${{ secrets.SERVER_IP }} "
            cd ${{ secrets.PROJECT_PATH }} &&
            git pull origin main &&
            npm install &&
            npm run build &&
            pm2 restart all
          "
